datasources:
  default:
    url: jdbc:h2:mem:devDb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: false
        allow_update_outside_transaction: false
    packages-to-scan: 'com.jegorovje.covidit.engine.data.entity.impl,com.jegorovje.covidit.security.data.entity'
server:
  cors:
    enabled: true
  maxRequestSize: 1000MB
  max-request-size: 1000MB
  multipart:
    max-file-size: 100MB
    max-request-size: 100MB
    maxFileSize: 100MB
    maxRequestSize: 100MB
    enabled: true
  http:
    client:
      read-timeout: 120s
h2:
  console:
    enabled: false
#kafka:
#  bootstrap:
#    servers: localhost:9092
micronaut:
  executors:
    scheduled:
      type: scheduled
      core-pool-size: 3
  security:
    token:
      propagation:
        enabled: true
      jwt:
        signatures:
          secret:
            generator:
              secret: "F7NVV7PnEiFm765hVzJSuasmomVWK0c-gB9ddH8T_5RLWTVjpDs-nGMX8sOf0wzHqPBnKy7mwj9hoQdUXt5OdE3d_6QsG5X9UFnQjBNALryKCaeqB0EPsveOhMNF06WlNKjhexns6fHbUwkLKbE6UCLPLlgoxavRFP79I9LkPM0"
        bearer:
          enabled: true
        enabled: true
      writer:
        header:
          enabled: true
    endpoints:
      oauth:
        enabled: true
      login:
        enabled: true
        path: "/login/token"
#  session:
#    http:
#      redis:
#        enabled: true
#         The Redis namespace to write sessions to
#        namespace: 'myapp:sessions'
#         Write session changes in the background
#        write-mode: BACKGROUND
#         Disable programatic activation of keyspace events
#        enable-keyspace-events: false
#redis:
#  uri: redis://localhost