package com.jegorovje.covidit.engine.util;

import java.util.HashMap;
import java.util.Map;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

public class CountryCodeMapperUtil {

  @AllArgsConstructor
  public static class Country{

    @Getter @Setter
    private String countryCode;

//    @Getter @Setter
    private String m49code;
  }
  public static Map<String, Country> map(){
    Map<String, Country> map = new HashMap<>();
    map.put("Afghanistan", new Country("AF", null));
    map.put("Åland Islands", new Country("AX", null));
    map.put("Albania", new Country("AL", null));
    map.put("Algeria", new Country("DZ", null));
    map.put("American Samoa", new Country("AS", null));
    map.put("Andorra", new Country("AD", null));
    map.put("Angola", new Country("AO", null));
    map.put("Anguilla", new Country("AI", null));
    map.put("Antarctica", new Country("AQ", null));
    map.put("Antigua and Barbuda", new Country("AG", null));
    map.put("Argentina", new Country("AR", null));
    map.put("Armenia", new Country("AM", null));
    map.put("Aruba", new Country("AW", null));
    map.put("Australia", new Country("AU", null));
    map.put("Austria", new Country("AT", null));
    map.put("Azerbaijan", new Country("AZ", null));
    map.put("Bahamas", new Country("BS", null));
    map.put("Bahrain", new Country("BH", null));
    map.put("Bangladesh", new Country("BD", null));
    map.put("Barbados", new Country("BB", null));
    map.put("Belarus", new Country("BY", null));
    map.put("Belgium", new Country("BE", null));
    map.put("Belize", new Country("BZ", null));
    map.put("Benin", new Country("BJ", null));
    map.put("Bermuda", new Country("BM", null));
    map.put("Bhutan", new Country("BT", null));
    map.put("Bolivia", new Country("BO", null));
    map.put("Bonaire; Sint Eustatius and Saba", new Country("BQ", null));
    map.put("Bosnia and Herzegovina", new Country("BA", null));
    map.put("Botswana", new Country("BW", null));
    map.put("Bouvet Island", new Country("BV", null));
    map.put("Brazil", new Country("BR", null));
    map.put("British Indian Ocean Territory", new Country("IO", null));
    map.put("Brunei", new Country("BN", null));
    map.put("Bulgaria", new Country("BG", null));
    map.put("Burkina Faso", new Country("BF", null));
    map.put("Burundi", new Country("BI", null));
    map.put("Cabo Verde", new Country("CV", null));
    map.put("Cambodia", new Country("KH", null));
    map.put("Cameroon", new Country("CM", null));
    map.put("Canada", new Country("CA", null));
    map.put("Cayman Islands", new Country("KY", null));
    map.put("CAR", new Country("CF", null));
    map.put("Chad", new Country("TD", null));
    map.put("Chile", new Country("CL", null));
    map.put("China", new Country("CN", null));
    map.put("Christmas Island", new Country("CX", null));
    map.put("Cocos (Keeling) Islands", new Country("CC", null));
    map.put("Colombia", new Country("CO", null));
    map.put("Comoros", new Country("KM", null));
    map.put("Congo", new Country("CG", null));
    map.put("DRC", new Country("CD", null));
    map.put("Cook Islands", new Country("CK", null));
    map.put("Costa Rica", new Country("CR", null));
    map.put("Ivory Coast", new Country("CI", null));
    map.put("Croatia", new Country("HR", null));
    map.put("Cuba", new Country("CU", null));
    map.put("Curaçao", new Country("CW", null));
    map.put("Cyprus", new Country("CY", null));
    map.put("Czechia", new Country("CZ", null));
    map.put("Denmark", new Country("DK", null));
    map.put("Djibouti", new Country("DJ", null));
    map.put("Dominica", new Country("DM", null));
    map.put("Dominican Republic", new Country("DO", null));
    map.put("Ecuador", new Country("EC", null));
    map.put("Egypt", new Country("EG", null));
    map.put("El Salvador", new Country("SV", null));
    map.put("Equatorial Guinea", new Country("GQ", null));
    map.put("Eritrea", new Country("ER", null));
    map.put("Estonia", new Country("EE", null));
    map.put("Ethiopia", new Country("ET", null));
    map.put("Falkland Islands", new Country("FK", null));
    map.put("Faeroe Islands", new Country("FO", null));
    map.put("Fiji", new Country("FJ", null));
    map.put("Finland", new Country("FI", null));
    map.put("France", new Country("FR", null));
    map.put("French Guiana", new Country("GF", null));
    map.put("French Polynesia", new Country("PF", null));
    map.put("French Southern Territories", new Country("TF", null));
    map.put("Gabon", new Country("GA", null));
    map.put("Gambia", new Country("GM", null));
    map.put("Georgia", new Country("GE", null));
    map.put("Germany", new Country("DE", null));
    map.put("Ghana", new Country("GH", null));
    map.put("Gibraltar", new Country("GI", null));
    map.put("Greece", new Country("GR", null));
    map.put("Greenland", new Country("GL", null));
    map.put("Grenada", new Country("GD", null));
    map.put("Guadeloupe", new Country("GP", null));
    map.put("Guam", new Country("GU", null));
    map.put("Guatemala", new Country("GT", null));
    map.put("Guernsey", new Country("GG", null));
    map.put("Guinea", new Country("GN", null));
    map.put("Guinea-Bissau", new Country("GW", null));
    map.put("Guyana", new Country("GY", null));
    map.put("Haiti", new Country("HT", null));
    map.put("Heard Island and McDonald Islands", new Country("HM", null));
    map.put("Holy See", new Country("VA", null));
    map.put("Honduras", new Country("HN", null));
    map.put("Hong Kong", new Country("HK", null));
    map.put("Hungary", new Country("HU", null));
    map.put("Iceland", new Country("IS", null));
    map.put("India", new Country("IN", null));
    map.put("Indonesia", new Country("ID", null));
    map.put("Iran", new Country("IR", null));
    map.put("Iraq", new Country("IQ", null));
    map.put("Ireland", new Country("IE", null));
    map.put("Isle of Man", new Country("IM", null));
    map.put("Israel", new Country("IL", null));
    map.put("Italy", new Country("IT", null));
    map.put("Jamaica", new Country("JM", null));
    map.put("Japan", new Country("JP", null));
    map.put("Jersey", new Country("JE", null));
    map.put("Jordan", new Country("JO", null));
    map.put("Kazakhstan", new Country("KZ", null));
    map.put("Kenya", new Country("KE", null));
    map.put("Kiribati", new Country("KI", null));
    map.put("Korea (Democratic People\"s Republic of)", new Country("KP", null));
    map.put("S. Korea", new Country("KR", null));
    map.put("Kuwait", new Country("KW", null));
    map.put("Kyrgyzstan", new Country("KG", null));
    map.put("Lao People\"s Democratic Republic", new Country("LA", null));
    map.put("Latvia", new Country("LV", null));
    map.put("Lebanon", new Country("LB", null));
    map.put("Lesotho", new Country("LS", null));
    map.put("Liberia", new Country("LR", null));
    map.put("Libya", new Country("LY", null));
    map.put("Liechtenstein", new Country("LI", null));
    map.put("Lithuania", new Country("LT", null));
    map.put("Luxembourg", new Country("LU", null));
    map.put("Macao", new Country("MO", null));
    map.put("North Macedonia", new Country("MK", null));
    map.put("Madagascar", new Country("MG", null));
    map.put("Malawi", new Country("MW", null));
    map.put("Malaysia", new Country("MY", null));
    map.put("Maldives", new Country("MV", null));
    map.put("Mali", new Country("ML", null));
    map.put("Malta", new Country("MT", null));
    map.put("Marshall Islands", new Country("MH", null));
    map.put("Martinique", new Country("MQ", null));
    map.put("Mauritania", new Country("MR", null));
    map.put("Mauritius", new Country("MU", null));
    map.put("Mayotte", new Country("YT", null));
    map.put("Mexico", new Country("MX", null));
    map.put("Micronesia", new Country("FM", null));
    map.put("Moldova", new Country("MD", null));
    map.put("Monaco", new Country("MC", null));
    map.put("Mongolia", new Country("MN", null));
    map.put("Montenegro", new Country("ME", null));
    map.put("Montserrat", new Country("MS", null));
    map.put("Morocco", new Country("MA", null));
    map.put("Mozambique", new Country("MZ", null));
    map.put("Myanmar", new Country("MM", null));
    map.put("Namibia", new Country("NA", null));
    map.put("Nauru", new Country("NR", null));
    map.put("Nepal", new Country("NP", null));
    map.put("Netherlands", new Country("NL", null));
    map.put("New Caledonia", new Country("NC", null));
    map.put("New Zealand", new Country("NZ", null));
    map.put("Nicaragua", new Country("NI", null));
    map.put("Niger", new Country("NE", null));
    map.put("Nigeria", new Country("NG", null));
    map.put("Niue", new Country("NU", null));
    map.put("Norfolk Island", new Country("NF", null));
    map.put("Northern Mariana Islands", new Country("MP", null));
    map.put("Norway", new Country("NO", null));
    map.put("Oman", new Country("OM", null));
    map.put("Pakistan", new Country("PK", null));
    map.put("Palau", new Country("PW", null));
    map.put("Palestine", new Country("PS", null));
    map.put("Panama", new Country("PA", null));
    map.put("Papua New Guinea", new Country("PG", null));
    map.put("Paraguay", new Country("PY", null));
    map.put("Peru", new Country("PE", null));
    map.put("Philippines", new Country("PH", null));
    map.put("Pitcairn", new Country("PN", null));
    map.put("Poland", new Country("PL", null));
    map.put("Portugal", new Country("PT", null));
    map.put("Puerto Rico", new Country("PR", null));
    map.put("Qatar", new Country("QA", null));
    map.put("Réunion", new Country("RE", null));
    map.put("Romania", new Country("RO", null));
    map.put("Russia", new Country("RU", null));
    map.put("Rwanda", new Country("RW", null));
    map.put("Saint Barth", new Country("BL", null));
    map.put("Saint Helena; Ascension and Tristan da Cunha", new Country("SH", null));
    map.put("Saint Kitts and Nevis", new Country("KN", null));
    map.put("Saint Lucia", new Country("LC", null));
    map.put("Saint Martin", new Country("MF", null));
    map.put("Saint Pierre Miquelon", new Country("PM", null));
    map.put("St. Vincent Grenadines", new Country("VC", null));
    map.put("Samoa", new Country("WS", null));
    map.put("San Marino", new Country("SM", null));
    map.put("Sao Tome and Principe", new Country("ST", null));
    map.put("Saudi Arabia", new Country("SA", null));
    map.put("Senegal", new Country("SN", null));
    map.put("Serbia", new Country("RS", null));
    map.put("Seychelles", new Country("SC", null));
    map.put("Sierra Leone", new Country("SL", null));
    map.put("Singapore", new Country("SG", null));
    map.put("Sint Maarten", new Country("SX", null));
    map.put("Slovakia", new Country("SK", null));
    map.put("Slovenia", new Country("SI", null));
    map.put("Solomon Islands", new Country("SB", null));
    map.put("Somalia", new Country("SO", null));
    map.put("South Africa", new Country("ZA", null));
    map.put("South Georgia and the South Sandwich Islands", new Country("GS", null));
    map.put("South Sudan", new Country("SS", null));
    map.put("Spain", new Country("ES", null));
    map.put("Sri Lanka", new Country("LK", null));
    map.put("Sudan", new Country("SD", null));
    map.put("Suriname", new Country("SR", null));
    map.put("Svalbard and Jan Mayen", new Country("SJ", null));
    map.put("Swaziland", new Country("SZ", null));
    map.put("Sweden", new Country("SE", null));
    map.put("Switzerland", new Country("CH", null));
    map.put("Syria", new Country("SY", null));
    map.put("Taiwan", new Country("TW", null));
    map.put("Tajikistan", new Country("TJ", null));
    map.put("Tanzania", new Country("TZ", null));
    map.put("Thailand", new Country("TH", null));
    map.put("Timor-Leste", new Country("TL", null));
    map.put("Togo", new Country("TG", null));
    map.put("Tokelau", new Country("TK", null));
    map.put("Tonga", new Country("TO", null));
    map.put("Trinidad and Tobago", new Country("TT", null));
    map.put("Tunisia", new Country("TN", null));
    map.put("Turkey", new Country("TR", null));
    map.put("Turkmenistan", new Country("TM", null));
    map.put("Turks and Caicos", new Country("TC", null));
    map.put("Tuvalu", new Country("TV", null));
    map.put("Uganda", new Country("UG", null));
    map.put("Ukraine", new Country("UA", null));
    map.put("UAE", new Country("AE", null));
    map.put("UK", new Country("GB", null));
    map.put("USA", new Country("US", null));
    map.put("United States Minor Outlying Islands", new Country("UM", null));
    map.put("Uruguay", new Country("UY", null));
    map.put("Uzbekistan", new Country("UZ", null));
    map.put("Vanuatu", new Country("VU", null));
    map.put("Venezuela", new Country("VE", null));
    map.put("Vietnam", new Country("VN", null));
    map.put("British Virgin Islands", new Country("VG", null));
    map.put("Virgin Islands USA", new Country("VI", null));
    map.put("Wallis and Futuna", new Country("WF", null));
    map.put("Western Sahara", new Country("EH", null));
    map.put("Yemen", new Country("YE", null));
    map.put("Zambia", new Country("ZM", null));
    map.put("Zimbabwe", new Country("ZW", null));
    map.put("World", new Country("N/A-1", null));
    map.put("Laos", new Country("N/A-2", null));
    map.put("Eswatini", new Country("N/A-3", null));
    map.put("Channel Islands", new Country("N/A-4", null));
    map.put("Diamond Princess", new Country("N/A-5", null));
    map.put("Caribbean Netherlands", new Country("N/A-6", null));
    map.put("St. Barth", new Country("N/A-7", null));
    map.put("Vatican City", new Country("N/A-8", null));
    map.put("MS Zaandam", new Country("N/A-9", null));
    return map;
  }
}
